export const T = {
  en: {
    farmer_portal:"Farmer Portal", language:"Language", profile_active:"Profile Active",
    region_central:"Central Region", region_western:"Western Region",
    region_eastern:"Eastern Region", region_northern:"Northern Region",
    nav_main:"Main", nav_dashboard:"Dashboard", nav_orders:"My Orders",
    nav_listings:"My Listings", nav_calendar:"Harvest Calendar",
    nav_finance:"Finance", nav_earnings:"Earnings", nav_momo:"MoMo Payments",
    nav_profile_sec:"Profile", nav_farm_profile:"My Farm Profile",
    nav_reviews:"My Reviews", nav_settings:"Settings",
    greeting:"Good morning, Emmanuel 👋",
    welcome_title:"Pineapple season is strong — Kayunga harvest underway",
    welcome_sub:"You have 3 active orders and 1 new order awaiting your response today.",
    view_orders:"View Orders →",
    stat_earnings:"This Month's Earnings", stat_earnings_sub:"↑ 18% vs last month",
    stat_orders:"Active Orders", stat_orders_sub:"1 new today",
    stat_listings:"Active Listings", stat_listings_sub:"Across 2 categories",
    stat_rating:"Average Rating", stat_rating_sub:"From 12 reviews",
    recent_orders:"Recent Orders", view_all:"View all",
    delivery:"Delivery", pickup:"Pickup",
    produce_pineapples:"Pineapples", produce_mangoes:"Mangoes",
    produce_passion:"Passion Fruit", produce_watermelon:"Watermelon",
    badge_new:"New", badge_confirmed:"Confirmed",
    badge_awaiting:"Awaiting pickup", badge_delivered:"Delivered ✓",
    quick_actions:"Quick Actions",
    qa_add_listing:"Add Listing", qa_add_sub:"Post produce for sale",
    qa_harvest:"Harvest Dates", qa_harvest_sub:"Update your calendar",
    qa_profile:"Edit Profile", qa_profile_sub:"Update your storefront",
    qa_withdraw:"Withdraw", qa_withdraw_sub:"Send to MoMo",
    regions_title:"Restaurant Demand by Region",
    view_all_regions:"See all regions",
    regions_desc:"Restaurants from these regions are actively buying produce. Your farm serves Central Region.",
    central_farmers:"142 active farmers · Your region",
    central_districts:"Kampala, Wakiso, Mukono, Kayunga, Luwero, Nakaseke, Mpigi",
    central_orders:"📦 187 orders this month",
    western_farmers:"89 active farmers",
    western_districts:"Mbarara, Kiruhura, Bushenyi, Fort Portal, Kabale, Masaka",
    western_orders:"📦 94 orders this month",
    eastern_farmers:"67 active farmers",
    eastern_districts:"Jinja, Mbale, Iganga, Tororo, Soroti, Kamuli",
    eastern_orders:"📦 48 orders this month",
    northern_farmers:"28 active farmers",
    northern_districts:"Gulu, Lira, Kitgum, Arua, Moroto",
    northern_orders:"📦 18 orders this month",
    upcoming_harvests:"Upcoming Harvests", manage_calendar:"Manage Calendar",
    est_200kg:"Est. 200kg available", est_150kg:"Est. 150kg available",
    est_400kg:"Est. 400kg available", est_80kg:"Est. 80kg available",
    new_order:"+ New Listing",
  },
  sw: {
    farmer_portal:"Lango la Mkulima", language:"Lugha",
    profile_active:"Wasifu Hai", region_central:"Mkoa wa Kati",
    region_western:"Mkoa wa Magharibi", region_eastern:"Mkoa wa Mashariki",
    region_northern:"Mkoa wa Kaskazini",
    nav_main:"Menyu Kuu", nav_dashboard:"Dashibodi", nav_orders:"Maagizo Yangu",
    nav_listings:"Bidhaa Zangu", nav_calendar:"Kalenda ya Mavuno",
    nav_finance:"Fedha", nav_earnings:"Mapato", nav_momo:"Malipo ya MoMo",
    nav_profile_sec:"Wasifu", nav_farm_profile:"Wasifu wa Shamba",
    nav_reviews:"Maoni Yangu", nav_settings:"Mipangilio",
    greeting:"Habari za asubuhi, Emmanuel 👋",
    welcome_title:"Msimu wa nanasi una nguvu — mavuno ya Kayunga yanaendelea",
    welcome_sub:"Una maagizo 3 yanayoendelea na agizo 1 jipya linakusubiria leo.",
    view_orders:"Ona Maagizo →",
    stat_earnings:"Mapato ya Mwezi Huu", stat_earnings_sub:"↑ 18% dhidi ya mwezi uliopita",
    stat_orders:"Maagizo Yanayoendelea", stat_orders_sub:"1 jipya leo",
    stat_listings:"Bidhaa Zinazofanya Kazi", stat_listings_sub:"Katika aina 2",
    stat_rating:"Ukadiriaji wa Wastani", stat_rating_sub:"Kutoka kwa maoni 12",
    recent_orders:"Maagizo ya Hivi Karibuni", view_all:"Ona yote",
    delivery:"Utoaji", pickup:"Kuchukua",
    produce_pineapples:"Nanasi", produce_mangoes:"Embe",
    produce_passion:"Matunda ya Pashen", produce_watermelon:"Tikiti maji",
    badge_new:"Jipya", badge_confirmed:"Imethibitishwa",
    badge_awaiting:"Inasubiri kuchukuliwa", badge_delivered:"Imetolewa ✓",
    quick_actions:"Vitendo vya Haraka",
    qa_add_listing:"Ongeza Bidhaa", qa_add_sub:"Weka mazao kuuzwa",
    qa_harvest:"Tarehe za Mavuno", qa_harvest_sub:"Sasisha kalenda yako",
    qa_profile:"Hariri Wasifu", qa_profile_sub:"Sasisha duka lako",
    qa_withdraw:"Toa Fedha", qa_withdraw_sub:"Tuma kwa MoMo",
    regions_title:"Mahitaji ya Mkahawa kwa Mkoa",
    view_all_regions:"Ona mikoa yote",
    regions_desc:"Migahawa kutoka mikoa hii inunua mazao kikamilifu. Shamba lako linahudumia Mkoa wa Kati.",
    central_farmers:"Wakulima 142 wanaofanya kazi · Mkoa wako",
    central_districts:"Kampala, Wakiso, Mukono, Kayunga, Luwero, Nakaseke, Mpigi",
    central_orders:"📦 Maagizo 187 mwezi huu",
    western_farmers:"Wakulima 89 wanaofanya kazi",
    western_districts:"Mbarara, Kiruhura, Bushenyi, Fort Portal, Kabale, Masaka",
    western_orders:"📦 Maagizo 94 mwezi huu",
    eastern_farmers:"Wakulima 67 wanaofanya kazi",
    eastern_districts:"Jinja, Mbale, Iganga, Tororo, Soroti, Kamuli",
    eastern_orders:"📦 Maagizo 48 mwezi huu",
    northern_farmers:"Wakulima 28 wanaofanya kazi",
    northern_districts:"Gulu, Lira, Kitgum, Arua, Moroto",
    northern_orders:"📦 Maagizo 18 mwezi huu",
    upcoming_harvests:"Mavuno Yanayokuja", manage_calendar:"Simamia Kalenda",
    est_200kg:"Wastani kg 200 zinapatikana", est_150kg:"Wastani kg 150 zinapatikana",
    est_400kg:"Wastani kg 400 zinapatikana", est_80kg:"Wastani kg 80 zinapatikana",
    new_order:"+ Bidhaa Mpya",
  },
  lg: {
    farmer_portal:"Entiriro y'Omulimi", language:"Olulimi",
    profile_active:"Porofayiro Nzijuvu", region_central:"Essaza ly'Ekibiina",
    region_western:"Essaza ly'Obulyoke", region_eastern:"Essaza ly'Obuvanjuba",
    region_northern:"Essaza ly'Omukiikulu",
    nav_main:"Akatale", nav_dashboard:"Dashibodi", nav_orders:"Emizigo Gyange",
    nav_listings:"Ebintu Byange", nav_calendar:"Kalenida y'Okukungula",
    nav_finance:"Ensimbi", nav_earnings:"Amagoba", nav_momo:"Okusasula MoMo",
    nav_profile_sec:"Porofayiro", nav_farm_profile:"Porofayiro y'Ennimiro",
    nav_reviews:"Ebivuga Byange", nav_settings:"Entegeka",
    greeting:"Wasuze otya, Emmanuel 👋",
    welcome_title:"Akasima k'enannasi kasaanidde — okukungula kwa Kayunga kukyali",
    welcome_sub:"Olina emizigo 3 egyokukolebwa ne muzigo 1 omupya ogukusubirira leero.",
    view_orders:"Laba Emizigo →",
    stat_earnings:"Amagoba g'Omwezi Guno", stat_earnings_sub:"↑ 18% okusinga omwezi oguwedde",
    stat_orders:"Emizigo Egyokukolebwa", stat_orders_sub:"1 empya leero",
    stat_listings:"Ebintu Ebyokukolebwa", stat_listings_sub:"Mu bigatteko 2",
    stat_rating:"Okubalibwa kw'Akatono", stat_rating_sub:"Okuva mu birowoozo 12",
    recent_orders:"Emizigo egy'Abanddeko", view_all:"Laba byonna",
    delivery:"Okutwalira", pickup:"Okujja okutwala",
    produce_pineapples:"Enannasi", produce_mangoes:"Emiyembe",
    produce_passion:"Ekibala ky'Amasimu", produce_watermelon:"Enkolokooto",
    badge_new:"Empya", badge_confirmed:"Etegekezeddwa",
    badge_awaiting:"Gw'okusubirira okutwala", badge_delivered:"Etwaliddwa ✓",
    quick_actions:"Ebikolwa Ebyangu",
    qa_add_listing:"Yongera Ekintu", qa_add_sub:"Teeka ebimera ku kuzaabira",
    qa_harvest:"Ennaku z'Okukungula", qa_harvest_sub:"Vvuunuula kalenida yo",
    qa_profile:"Kyusa Porofayiro", qa_profile_sub:"Vvuunuula dduka lyo",
    qa_withdraw:"Ssa Ensimbi", qa_withdraw_sub:"Tuma ku MoMo",
    regions_title:"Okwetaaga kw'Essuuka ku Ssaza",
    view_all_regions:"Laba essaza lyonna",
    regions_desc:"Essuuka okuva mu bissaza bino zigula ebimera. Ennimiro yo enyamba Essaza ly'Ekibiina.",
    central_farmers:"Abalimi 142 abakolebwa · Essaza lyo",
    central_districts:"Kampala, Wakiso, Mukono, Kayunga, Luwero, Nakaseke, Mpigi",
    central_orders:"📦 Emizigo 187 mu mwezi guno",
    western_farmers:"Abalimi 89 abakolebwa",
    western_districts:"Mbarara, Kiruhura, Bushenyi, Fort Portal, Kabale, Masaka",
    western_orders:"📦 Emizigo 94 mu mwezi guno",
    eastern_farmers:"Abalimi 67 abakolebwa",
    eastern_districts:"Jinja, Mbale, Iganga, Tororo, Soroti, Kamuli",
    eastern_orders:"📦 Emizigo 48 mu mwezi guno",
    northern_farmers:"Abalimi 28 abakolebwa",
    northern_districts:"Gulu, Lira, Kitgum, Arua, Moroto",
    northern_orders:"📦 Emizigo 18 mu mwezi guno",
    upcoming_harvests:"Okukungula Okujja", manage_calendar:"Lowooza Kalenida",
    est_200kg:"Okutereeza kg 200 zinaabaawo", est_150kg:"Okutereeza kg 150 zinaabaawo",
    est_400kg:"Okutereeza kg 400 zinaabaawo", est_80kg:"Okutereeza kg 80 zinaabaawo",
    new_order:"+ Ekintu Ekipya",
  }
};

export const orders = [
  { id: 1, icon: '🍽️', title: 'Kati Kati Restaurant', amount: 'UGX 200K', badgeType: 'new', badgeKey: 'badge_new', metaParts: ['40kg', 'produce_pineapples', 'delivery', 'Fri 4 Apr', 'region_central'] },
  { id: 2, icon: '🏨', title: 'Serena Hotel Kampala', amount: 'UGX 175K', badgeType: 'confirmed', badgeKey: 'badge_confirmed', metaParts: ['25kg', 'produce_mangoes', 'Thu 3 Apr', 'region_central'] },
  { id: 3, icon: '☕', title: 'Café Javas — Oasis Mall', amount: 'UGX 80K', badgeType: 'pending', badgeKey: 'badge_awaiting', metaParts: ['10kg', 'produce_passion', 'pickup', 'region_central'] },
  { id: 4, icon: '🍕', title: 'Mamba Point Restaurant', amount: 'UGX 120K', badgeType: 'delivered', badgeKey: 'badge_delivered', metaParts: ['30kg', 'produce_watermelon', '27 Mar', 'region_central'] }
];

export const regions = [
  { id: 'central', type: 'central', icon: '🌿', nameKey: 'region_central', farmersKey: 'central_farmers', districtsKey: 'central_districts', ordersKey: 'central_orders', active: true },
  { id: 'western', type: 'western', icon: '🥛', nameKey: 'region_western', farmersKey: 'western_farmers', districtsKey: 'western_districts', ordersKey: 'western_orders', active: false },
  { id: 'eastern', type: 'eastern', icon: '🍍', nameKey: 'region_eastern', farmersKey: 'eastern_farmers', districtsKey: 'eastern_districts', ordersKey: 'eastern_orders', active: false },
  { id: 'northern', type: 'northern', icon: '🌾', nameKey: 'region_northern', farmersKey: 'northern_farmers', districtsKey: 'northern_districts', ordersKey: 'northern_orders', active: false },
];

export const harvests = [
  { id: 1, month: 'APR', day: '8', icon: '🍍', produceKey: 'produce_pineapples', qtyKey: 'est_200kg', regionKey: 'region_central' },
  { id: 2, month: 'APR', day: '14', icon: '🥭', produceKey: 'produce_mangoes', qtyKey: 'est_150kg', regionKey: 'region_central' },
  { id: 3, month: 'MAY', day: '3', icon: '🍉', produceKey: 'produce_watermelon', qtyKey: 'est_400kg', regionKey: 'region_central' },
  { id: 4, month: 'MAY', day: '20', icon: '🍋', produceKey: 'produce_passion', qtyKey: 'est_80kg', regionKey: 'region_central' }
];

export const stats = [
  { id: 1, type: 'g', icon: '💰', labelKey: 'stat_earnings', val: 'UGX 842K', subKey: 'stat_earnings_sub' },
  { id: 2, type: 'b', icon: '📦', labelKey: 'stat_orders', val: '3', subKey: 'stat_orders_sub' },
  { id: 3, type: 'o', icon: '🥬', labelKey: 'stat_listings', val: '7', subKey: 'stat_listings_sub' },
  { id: 4, type: 'n', icon: '⭐', labelKey: 'stat_rating', val: '4.8', subKey: 'stat_rating_sub' }
];

export const quickActions = [
  { id: 1, icon: '➕', labelKey: 'qa_add_listing', subKey: 'qa_add_sub' },
  { id: 2, icon: '📅', labelKey: 'qa_harvest', subKey: 'qa_harvest_sub' },
  { id: 3, icon: '👤', labelKey: 'qa_profile', subKey: 'qa_profile_sub' },
  { id: 4, icon: '💸', labelKey: 'qa_withdraw', subKey: 'qa_withdraw_sub' }
];
