"use client";
import React, { createContext, useContext, useState, ReactNode } from 'react';

type LanguageContextType = {
  lang: string;
  setLang: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState('en');

  // Simple translations mapping
  const translations: Record<string, Record<string, string>> = {
    en: {
      farmer_portal: 'FARMER PORTAL',
      language: 'Language',
      profile_active: 'Active',
      region_central: 'Central Region',
      nav_main: 'MAIN MENU',
      nav_dashboard: 'Dashboard',
      nav_orders: 'Orders',
      nav_listings: 'My Listings',
      nav_calendar: 'Harvest Calendar',
      nav_finance: 'FINANCE',
      nav_earnings: 'Earnings',
      nav_momo: 'MoMo Payments',
      nav_profile_sec: 'FARM & PROFILE',
      nav_farm_profile: 'Farm Profile',
      nav_reviews: 'Reviews',
      nav_settings: 'Settings',
      greeting_morning: 'Good morning',
      greeting_afternoon: 'Good afternoon',
      greeting_evening: 'Good evening',
      new_order: 'New Order',
      welcome_title: 'Your crops are in high demand!',
      welcome_sub: 'You have 3 new orders pending confirmation.',
      view_orders: 'View Orders',
      stat_earnings: 'Total Earnings',
      stat_orders: 'Active Orders',
      stat_crops: 'Listed Crops',
      stat_rating: 'Farm Rating',
      this_month: 'This month',
      awaiting_conf: 'Awaiting confirmation',
      in_stock: 'In stock',
      from_reviews: 'From 24 reviews',
      recent_orders: 'Recent Orders',
      view_all: 'View All',
      quick_actions: 'Quick Actions',
      add_listing: 'Add Listing',
      update_stock: 'Update Stock',
      req_payout: 'Request Payout',
      contact_support: 'Contact Support',
      regions_title: 'Regional Insights',
      view_all_regions: 'View Map',
      regions_desc: 'Demand and pricing trends across different regions.',
      upcoming_harvests: 'Upcoming Harvests',
      manage_calendar: 'Manage Calendar',
      status_new: 'New',
      status_conf: 'Confirmed',
      status_del: 'Delivered',
      status_pend: 'Pending',
      r_central: 'Central',
      r_western: 'Western',
      r_eastern: 'Eastern',
      r_northern: 'Northern',
      f_count: '1,240 Farmers',
      f_count_w: '850 Farmers',
      f_count_e: '620 Farmers',
      f_count_n: '410 Farmers',
      d_central: 'Kampala, Wakiso, Mukono',
      d_western: 'Mbarara, Kabale, Kasese',
      d_eastern: 'Jinja, Mbale, Soroti',
      d_northern: 'Gulu, Lira, Arua',
      o_high: 'High Demand',
      o_med: 'Medium Demand',
      o_low: 'Low Demand',
      p_matooke: 'Matooke',
      p_coffee: 'Coffee Beans',
      p_maize: 'Maize',
      p_beans: 'Beans',
      qty_bunches: '50 Bunches',
      qty_bags: '20 Bags',
      qty_kg: '500 kg',
      time_days: 'in 2 days',
      time_weeks: 'in 1 week'
    },
    sw: {
      farmer_portal: 'KITUO CHA MKULIMA',
      language: 'Lugha',
      profile_active: 'Inatumika',
      region_central: 'Kanda ya Kati',
      nav_main: 'MENU KUU',
      nav_dashboard: 'Dashibodi',
      nav_orders: 'Oda',
      nav_listings: 'Orodha Zangu',
      nav_calendar: 'Kalenda ya Mavuno',
      nav_finance: 'FEDHA',
      nav_earnings: 'Mapato',
      nav_momo: 'Malipo ya MoMo',
      nav_profile_sec: 'SHAMBA NA WASIFU',
      nav_farm_profile: 'Wasifu wa Shamba',
      nav_reviews: 'Maoni',
      nav_settings: 'Mipangilio',
      greeting_morning: 'Habari ya asubuhi',
      greeting_afternoon: 'Habari ya mchana',
      greeting_evening: 'Habari ya jioni',
      new_order: 'Oda Mpya',
      welcome_title: 'Mazao yako yanahitajika sana!',
      welcome_sub: 'Una oda 3 mpya zinazosubiri uthibitisho.',
      view_orders: 'Tazama Oda',
      stat_earnings: 'Jumla ya Mapato',
      stat_orders: 'Oda Zinazoendelea',
      stat_crops: 'Mazao Yaliyoorodheshwa',
      stat_rating: 'Kiwango cha Shamba',
      this_month: 'Mwezi huu',
      awaiting_conf: 'Zinasubiri uthibitisho',
      in_stock: 'Kwenye hisa',
      from_reviews: 'Kutoka maoni 24',
      recent_orders: 'Oda za Hivi Karibuni',
      view_all: 'Tazama Zote',
      quick_actions: 'Vitendo vya Haraka',
      add_listing: 'Ongeza Orodha',
      update_stock: 'Sasisha Hisa',
      req_payout: 'Omba Malipo',
      contact_support: 'Wasiliana na Usaidizi',
      regions_title: 'Mwelekeo wa Kanda',
      view_all_regions: 'Tazama Ramani',
      regions_desc: 'Mwelekeo wa mahitaji na bei katika kanda tofauti.',
      upcoming_harvests: 'Mavuno Yajayo',
      manage_calendar: 'Dhibiti Kalenda',
      status_new: 'Mpya',
      status_conf: 'Imethibitishwa',
      status_del: 'Imewasilishwa',
      status_pend: 'Inasubiri',
      r_central: 'Kati',
      r_western: 'Magharibi',
      r_eastern: 'Mashariki',
      r_northern: 'Kaskazini',
      f_count: 'Wakulima 1,240',
      f_count_w: 'Wakulima 850',
      f_count_e: 'Wakulima 620',
      f_count_n: 'Wakulima 410',
      d_central: 'Kampala, Wakiso, Mukono',
      d_western: 'Mbarara, Kabale, Kasese',
      d_eastern: 'Jinja, Mbale, Soroti',
      d_northern: 'Gulu, Lira, Arua',
      o_high: 'Mahitaji Makubwa',
      o_med: 'Mahitaji ya Kati',
      o_low: 'Mahitaji Madogo',
      p_matooke: 'Matooke',
      p_coffee: 'Maharage ya Kahawa',
      p_maize: 'Mahindi',
      p_beans: 'Maharage',
      qty_bunches: 'Mikungu 50',
      qty_bags: 'Mifuko 20',
      qty_kg: 'Kilo 500',
      time_days: 'baada ya siku 2',
      time_weeks: 'baada ya wiki 1'
    },
    lg: {
      farmer_portal: 'AWAKUBA OMULIMI',
      language: 'Olwimi',
      profile_active: 'Akola',
      region_central: 'Masekati',
      nav_main: 'MENYU ENKULU',
      nav_dashboard: 'Deshiboodi',
      nav_orders: 'Oda',
      nav_listings: 'Ebirime byange',
      nav_calendar: 'Kalenda y\'amakungula',
      nav_finance: 'EBYENFIMBA',
      nav_earnings: 'Ennyingiza',
      nav_momo: 'Okusasula kwa MoMo',
      nav_profile_sec: 'FAAMU & PULOFAYIRO',
      nav_farm_profile: 'Pulofayiro ya Faamu',
      nav_reviews: 'Okwekenneenya',
      nav_settings: 'Enteekateeka',
      greeting_morning: 'Wasuze otya',
      greeting_afternoon: 'Osiibye otya',
      greeting_evening: 'Osiibye otya',
      new_order: 'Oda Empya',
      welcome_title: 'Ebirime byo byetaagibwa nnyo!',
      welcome_sub: 'Olina oda 3 empya ezirinda okukakasibwa.',
      view_orders: 'Laba Oda',
      stat_earnings: 'Omuwendo gw\'ennyingiza',
      stat_orders: 'Oda ezikola',
      stat_crops: 'Ebirime ebiragiddwa',
      stat_rating: 'Ekipimo kya Faamu',
      this_month: 'Omwezi guno',
      awaiting_conf: 'Zirinda okukakasibwa',
      in_stock: 'Ziri mu sitoowa',
      from_reviews: 'Okuva mu kwekenneenya 24',
      recent_orders: 'Oda z\'akaseera kano',
      view_all: 'Laba Zonna',
      quick_actions: 'Ebikolebwa amangu',
      add_listing: 'Yongerako Ekirime',
      update_stock: 'Tereeza Sitoowa',
      req_payout: 'Saba Okusasulwa',
      contact_support: 'Tuukirira Obuyambi',
      regions_title: 'Ebifa mu Bitundu',
      view_all_regions: 'Laba Maapu',
      regions_desc: 'Omugendo gw\'ebyetaago n\'emiwendo mu bitundu eby\'enjawulo.',
      upcoming_harvests: 'Amakungula Agajja',
      manage_calendar: 'Fuga Kalenda',
      status_new: 'Mpya',
      status_conf: 'Ekakasiddwa',
      status_del: 'Etuusiddwa',
      status_pend: 'Erindiridde',
      r_central: 'Masekati',
      r_western: 'Bugwanjuba',
      r_eastern: 'Buvanjuba',
      r_northern: 'Mambuka',
      f_count: 'Abalimi 1,240',
      f_count_w: 'Abalimi 850',
      f_count_e: 'Abalimi 620',
      f_count_n: 'Abalimi 410',
      d_central: 'Kampala, Wakiso, Mukono',
      d_western: 'Mbarara, Kabale, Kasese',
      d_eastern: 'Jinja, Mbale, Soroti',
      d_northern: 'Gulu, Lira, Arua',
      o_high: 'Ebyetaago Bingi',
      o_med: 'Ebyetaago bya Makkati',
      o_low: 'Ebyetaago Bitono',
      p_matooke: 'Matooke',
      p_coffee: 'Emmwanyi',
      p_maize: 'Kasooli',
      p_beans: 'Ebijanjaalo',
      qty_bunches: 'Enkoko 50',
      qty_bags: 'Ensawo 20',
      qty_kg: 'Kkiro 500',
      time_days: 'mu nnaku 2',
      time_weeks: 'mu wiiki 1'
    }
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLang must be used within LanguageProvider');
  }
  return context;
};
